### ISSUE TITLE
Search returns 0 result with culture set

### ISSUE THREAD

**Issue by aguyfromdenmark** [skttl/Our.Umbraco.FullTextSearch#24] opened 2020-05-11 11:01 UTC
Search using `.SetCulture(model.Content.GetCultureFromDomains().ToLower())` return 0 results. 
Search without setting culture returns the expected amount of results. 

Site is set to "da-dk" in Umbraco, and that is also returned and passed to `SetCulture()`.

- Umbraco 8.5.5
- Package v. 0.2.0

**Comment by skttl** [comment] 2020-05-28 18:01
This a duplicate of #4, but the issue hasn't been fixed completely.

**Closed** 2020-06-03 21:04 UTC
